<script setup lang="ts">
  import { computed, watch, ref, onMounted } from 'vue';
  import useStore from '@/stores/store';
  import { useRoute } from 'vue-router';
  import type { Product, ServerError } from '@/models';
  import ErrorMessage from '@/components/ErrorMessage.vue';

  const props = defineProps<{
    selectedCategories: number[];
  }>();
  const store = useStore();
  const route = useRoute();
  const selectedCategories = computed(() => props.selectedCategories);
  const products = ref<Product[] | undefined>([]);
  const errorData = ref<ServerError>();

  onMounted(async () => {
    await getProducts();
  });

  watch(selectedCategories, async () => {
    await getProducts();
  });

  const getProducts = async () => {
    try {
      products.value = await store.getProducts({ categories: selectedCategories.value.join(',') });
    } catch (error: any) {
      errorData.value = error;
    }
  };

  const onBuyClick = (product: Product) => {
    store.addProductToCart(product);
  };
</script>

<template>
  <template v-if="errorData">
    <ErrorMessage :error-data="errorData"></ErrorMessage>
  </template>
  <template v-else>
    <h1 class="block-title">Products</h1>

    <div>
      <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col" v-for="product in products" :key="product.id">
          <RouterLink
            class="card h-100 text-decoration-none"
            :to="{ name: 'ProductItem', params: { slug: `${product.autogeneratedSlug}-id-${product.id}` }, query: { ...route.query } }"
          >
            <img :src="product.imageUrl" class="card-img-top" :alt="product.name" />
            <div class="card-body text-center">
              <p class="card-title fs-6 fw-light text-uppercase">{{ product.name }}</p>
              <p class="card-text fs-6 fw-light">{{ product.defaultDisplayedPriceFormatted }}</p>
            </div>
            <div class="card-footer d-flex justify-content-center">
              <button title="Buy" class="btn btn-primary" @click.prevent="onBuyClick(product)">Buy</button>
            </div>
          </RouterLink>
        </div>
      </div>
    </div>
  </template>
</template>

<style scoped lang="scss"></style>
