<script setup lang="ts">
  import type { CartProduct } from '@/models';
  import useStore from '@/stores/store';
  import { storeToRefs } from 'pinia';
  import { ref } from 'vue';
  import ModalComponent from '@/components/ModalComponent.vue';
  import { useRouter } from 'vue-router';

  const store = useStore();
  const router = useRouter();
  const { cartProducts, getCartProductsTotalPrice } = storeToRefs(store);
  const onPlaceOrderClicked = ref(false);

  const increaseQuantity = (product: CartProduct) => {
    store.increaseProductQuantity(product);
  };
  const decreaseQuantity = (product: CartProduct) => {
    store.decreaseProductQuantity(product);
  };
  const deleteProductFromCart = (product: CartProduct) => {
    store.removeProductFromCart(product);
  };
  const onPlaceOrder = () => {
    store.clearCart();
    onPlaceOrderClicked.value = false;
    router.push({ name: 'HomePage' });
  };
</script>

<template>
  <div class="container mt-4 mb-5">
    <div class="row">
      <div class="col-12">
        <h1 class="block-title">Shopping Cart</h1>

        <template v-if="cartProducts.length">
          <div class="card mb-3" v-for="product in cartProducts" :key="product.id">
            <RouterLink
              class="card h-100 text-decoration-none"
              :to="{ name: 'ProductItem', params: { slug: `${product.autogeneratedSlug}-id-${product.id}` } }"
            >
              <div class="row g-0 align-items-center">
                <div class="col-md-1">
                  <img :src="product.imageUrl" class="img-fluid rounded-start" :alt="product.name" />
                </div>
                <div class="col-md-5">
                  <div class="card-body">
                    <div class="d-flex align-items-start justify-content-center justify-content-md-start">
                      <div class="text-center text-md-start">
                        <p class="card-title fs-6 fw-light text-uppercase">{{ product.name }}</p>
                        <p class="mb-0">{{ product.defaultDisplayedPriceFormatted }}</p>
                      </div>
                      <button title="Delete" type="button" class="btn btn-sm btn-outline-danger ms-4" @click.prevent="deleteProductFromCart(product)">
                        <i class="bi bi-trash3"></i>
                      </button>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 pe-3 pb-3 pb-md-0">
                  <div class="d-flex flex-column align-items-center align-items-md-end">
                    <p class="fs-3 mb-1 fw-light">{{ product.totalPrice }} €</p>
                    <div class="d-flex align-items-center">
                      <button title="Decrease by 1" type="button" class="btn btn-sm btn-outline-primary" @click.prevent="decreaseQuantity(product)">
                        <i class="bi bi-dash-lg"></i>
                      </button>
                      <div class="px-3">{{ product.quantity }} pcs.</div>
                      <button title="Increase by 1" type="button" class="btn btn-sm btn-outline-primary" @click.prevent="increaseQuantity(product)">
                        <i class="bi bi-plus-lg"></i>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </RouterLink>
          </div>
          <div class="d-flex flex-column justify-content-center align-items-center">
            <p class="fs-4 fw-light mb-0 mt-3">Total: {{ getCartProductsTotalPrice }} €</p>
            <div>
              <button title="Place Order" class="btn btn-primary mt-3" @click="onPlaceOrderClicked = true">Place Order</button>
            </div>
            <ModalComponent :isOpen="onPlaceOrderClicked" @modal-close="onPlaceOrder">
              <template #header>
                <h4 class="alert-heading fw-light fs-3">Congratulations! 🎉</h4>
              </template>
              <template #content>
                <p class="text-center"
                  >Your order has been placed. <br />
                  Thank you for shopping with us!</p
                >
              </template>
            </ModalComponent>
          </div>
        </template>
        <template v-else>
          <div class="alert alert-primary" role="alert">
            Your cart is empty. <RouterLink class="alert-link fw-medium" :to="{ name: 'HomePage' }">View products</RouterLink>
          </div>
        </template>
      </div>
    </div>
  </div>
</template>

<style scoped></style>
