import type { Translations } from './common';

export interface Category {
  id: number;
  orderBy: number;
  name: string;
  nameTranslated: Translations;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  description: string;
  descriptionTranslated: Translations;
  enabled: boolean;
  isSampleCategory: boolean;
  seoTitle: string;
  seoDescription: string;
  alt: Translations;
}
