import type { ImageDetails, Translations } from './common';
import type { BorderInfo } from './product';

export interface Category {
  id: number;
  orderBy: number;
  hdThumbnailUrl: string;
  thumbnailUrl: string;
  originalImageUrl: string;
  imageUrl: string;
  originalImage: ImageDetails;
  thumbnail: ImageDetails;
  borderInfo: BorderInfo;
  name: string;
  nameTranslated: Translations;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  description: string;
  descriptionTranslated: Translations;
  enabled: boolean;
  isSampleCategory: boolean;
  seoTitle: string;
  seoDescription: string;
  alt: Translations;
}
